// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Ka0CnGPZUhSmhFxP5CoAUY0Qr5RVGsI',
    appId: '1:535569013217:web:1ccfca625987a3b3b35aa0',
    messagingSenderId: '535569013217',
    projectId: 'noteme-e20c5',
    authDomain: 'noteme-e20c5.firebaseapp.com',
    storageBucket: 'noteme-e20c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6jUk_9PQeRUkVcWKdBmqCPGwPv0tE-JA',
    appId: '1:535569013217:android:7efc610c2c549134b35aa0',
    messagingSenderId: '535569013217',
    projectId: 'noteme-e20c5',
    storageBucket: 'noteme-e20c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiX5yydXapLeO7NcSIqJKzxEhCwlz0nf8',
    appId: '1:535569013217:ios:d797faabacd53cfcb35aa0',
    messagingSenderId: '535569013217',
    projectId: 'noteme-e20c5',
    storageBucket: 'noteme-e20c5.firebasestorage.app',
    iosBundleId: 'com.example.noteme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiX5yydXapLeO7NcSIqJKzxEhCwlz0nf8',
    appId: '1:535569013217:ios:d797faabacd53cfcb35aa0',
    messagingSenderId: '535569013217',
    projectId: 'noteme-e20c5',
    storageBucket: 'noteme-e20c5.firebasestorage.app',
    iosBundleId: 'com.example.noteme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Ka0CnGPZUhSmhFxP5CoAUY0Qr5RVGsI',
    appId: '1:535569013217:web:3fb0a12918213e69b35aa0',
    messagingSenderId: '535569013217',
    projectId: 'noteme-e20c5',
    authDomain: 'noteme-e20c5.firebaseapp.com',
    storageBucket: 'noteme-e20c5.firebasestorage.app',
  );
}
